### ISSUE TITLE
Packet loss missing data

### ISSUE THREAD

**Issue by arnowelzel** [Splo0sh/netdata_ts3_plugin#12]
Usually the packet loss shows four values:

- speech
- keepalive
- control
- total

However, in my case very often one or more values are just not there. For example at the moment I have only "control" and "total" but "keepalive" and "speech" are missing - even thought there are three users connected:

![image](https://user-images.githubusercontent.com/6613614/41425162-3444c418-7000-11e8-8aca-8c50bcabba73.png)

The server is TeamSpeak 3.2.0, Linux-x86_64 running on Ubuntu 16.04

Any idea?

**Comment by coraxx** [comment]
I‘m pretty sure NetData only shows graphs for non-zero values to save memory.

**Comment by arnowelzel** [comment]
That's strange - because if **all** values are 0, then the chart is displayed properly:

![grafik](https://user-images.githubusercontent.com/6613614/41462147-2cfb99e2-7092-11e8-82c9-826d1b86b346.png)

I have to investigate this a bit further. Is it possible, that TeamSpeak sometimes just does not report packet loss values of a specific category?

**Comment by arnowelzel** [comment]
I could fix this issue by adding the parameter `chart_cleanup: 0` to `ts3.conf`:

```
local:
    update_every: 1
    priority: 60000
    retries: 10
    host: '127.0.0.1'
    port: 10011
    sid: 1
    user: '**secret**'
    pass: '**secret**'
    chart_cleanup: 0
```

I'm not sure yet, if certain data sources are really just missing sometimes and therefore netdata cleans up the chart - but with this parameter added, at least the data sources will not just disappear any longer.
